dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.54.0
  - secure: R90DoWlOuvdqzNnhfjo17hhYQcKc77thapOW5leDdIBfN9EZfOlqRRgtN1HSFH/RRV73cIAZDVBp8HY+uBoDGfVg9gXYrbIdBW5cnOXVpXrZZTQevbvldZwz805ybqiP+JjnoFyp1Pjqat0iyc3UOU4x82jGQdadOMz++d7iH31OiJ/sH4nygvLoqfGCwJyOcHSNcAjo5DOU99reksYlkh8H4bBmnRAtiMIfzpRNRwhnvQMrKEhXoxWkxbj1bRIWx8znnRNyazuGjs8rFyClZOwVRzUA4CohhE8PUkG9CRKGrfErJslY8fqBk4ZTAL9hspTEVjVewEx8pTPe9rq1yzh7OSDWSb2EZGJPpGwrPN3Qn8FEKAic1RoRsJRuECSHEj/aaoKD9Xcqu0zB/CdHkHTDI4eR2lggEce55szVg7qQBD++6n/f8cwiptInAOryWtquepHfhj6w8TmMwIH+e28DelU4PokCwfmgMKS0DDrUVdNm/jE9f73uS3iSX36r9yvTp3Jm9uox6yJH73w/8Rs4N3VRs+qrxVg7r6w0ySI3ME3bgpc75VNd2GZFsF8Uh9PPenXcL4KthbkZre1URLDMtooGrUngoZ1O488tEyqRGlQ2QYEzZJ+OjzFaOtD4q7iIuTm2GiB16wfPo3xBxaxeq1Fre1NWsJuQXfBYdyQ=
  - secure: gzwr37Erzi7RwjGHeg6bcYVWpYtDiMwy0/WgLHyCmAtBTRb7vtjtMSS/B6+jFaTBpib4oPyyMLGAQnuelr7sDgOnpz5bcdHps61mMH1wec873s8LW//8WqahItF6RP2JKo985iVLDUwqVUhAHvkyifqQKWicDipZvttp9Zh6baDa9vrkADhFcUouqWy3BUojjHGg+PlsMZQ5W92OjaVScVhn+cOtcV6blMRtKjmyW3Q++opcL5De0N/p5DiBNp5edA+WVE2oHBMz1y9OOziQ0UYYyXCyMEAmOdnUosrYFf6QWO7FMAFNbM0G+Ya4b0FtylXmLwfmk9ESbzilapBFw0uKOV921h2NoxgKW4/AK5vrVChosYZBxH6AgkrkB4eoi9GbLcKL9q2eUfZKrgT7Hu772LzoCQJ4pGUrlT+/ZDqsVLbQv1kB7SFNVBFCWwJHuUrBve7gCvAhP7dqXLkBuP+K3/wyoH/UsUeXGDcEkVQxZSbqS8R8B78a4GnTESETaGkXLA1LaBLTROMTPQhxTS0qmc6MUMbiOm0hTXejkCtq3BjXB7qq7ZbqIXyojyahUMpST6K1+JVaw01NvWBOQmqAYMcYgAiAYjCWeSDy6Y3Sn/5uguZ5itZJ6SfJ11rzFeEzV3uKaLb3X8bx+7PM6kzJwNbVzy6VB3Fc2wlAtmY=
  - secure: uAUvx2SZCX8STCv5TDxPz74cjPPPQl9+Gou/QWp8ZjAjY6ZjuYTnCnGDL6i3D07K849yvA1FriTNAbiaAS8mO/bjEsaDTjc/5dDHyvROZYM4KQbisGzSfz/41UoWmSGJ0BHVZcsmOUBbqMp/VswSDVo5mEtdw1VXZV5q8Z6DXQxCiNaM6Mm5eFaNjkIcoHv4v6n936ummWjwCvynI/NsE9yPtyu+rsEcjL22oh8FyjzmATDseQeLxej5oowBMgML9tBLXRTmhAsSH4GRU2P6M3HEnp7X1fwrg5IKbNvqtadTyNevCgX68kHaBTLTDDhFHlAt0XHnK98AXPe+hu28JQMHYwqpguF6lrH7ICpSvxQwFjiKQbIofBjMGKWvF4uGeK9vWmgJzkTVMej/Ja7SaUUZ9HJcXOQMqueOg4AfWcDvVRDzBxKtECLx4NxGmXwxRXy41FtQZecP/ASxWtdqgLXhy5bfip1itBd0gkhl7zV2oHMOPgVIcOBDAIVA75EsDicVRxTb2Siuxe5UjgsN7FynUalnsEWxM67aZGkQGr4gvX8s3GhVjRd+tBAsP+Q7RNExmXhMLhWTjwCyhBUnUQdzI6qN06JQPLOH3CawLADc6l1Hhz+g9CzbUmuzv2YxK8liZydfLuZSz+b4SNJZ4aVEc5LcKveo0MncrMs5Zbk=
before_deploy:
  - openssl aes-256-cbc -K $encrypted_dbf1609e2015_key -iv $encrypted_dbf1609e2015_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master