version: 2
jobs:
  
  build_hugo:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

  conf_ftp:
    docker:
      - image: circleci/node:latest
    steps:
      - run: npm install
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  version: 2
  deploy:
    jobs:
      - build_hugo:
          filters:
            branches:
              only:
                - master
      - conf_ftp:
          filters:
            branches:
              only:
                - master