version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git && apk add lftp
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - checkout
      - run: lftp sftp://${username}:${password}@${host} -e "mirror -v -R --exclude .git/ --exclude .circleci/ ./ enprod/; quit"
      - run: scp -r ./ "${username}@$${host}:/enprod"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master